const CARDS = [
  { hanzi: "你好", pinyin: "nǐ hǎo",    translation: "olá" },
  { hanzi: "谢谢", pinyin: "xiè xie",   translation: "obrigado(a)" },
  { hanzi: "再见", pinyin: "zài jiàn",  translation: "até logo / tchau" },
  { hanzi: "爱",   pinyin: "ài",        translation: "amor / amar" },
  { hanzi: "水",   pinyin: "shuǐ",      translation: "água" },
  { hanzi: "朋友", pinyin: "péng you",  translation: "amigo(a)" },
  { hanzi: "中国", pinyin: "zhōng guó", translation: "China" },
  { hanzi: "学生", pinyin: "xué sheng", translation: "estudante" },
  { hanzi: "老师", pinyin: "lǎo shī",   translation: "professor(a)" },
  { hanzi: "今天", pinyin: "jīn tiān",  translation: "hoje" },
  { hanzi: "火车", pinyin: "huǒ chē",   translation: "trem" },
  { hanzi: "早餐", pinyin: "zǎo cān",   translation: "café da manhã" },
  { hanzi: "午餐", pinyin: "wǔ cān",    translation: "almoço" },
  { hanzi: "晚餐", pinyin: "wǎn cān",   translation: "jantar" },
  { hanzi: "昨天", pinyin: "zuó tiān",  translation: "ontem" },
  { hanzi: "明天", pinyin: "míng tiān", translation: "amanhã" },
  { hanzi: "火",   pinyin: "huǒ",       translation: "fogo" },
  { hanzi: "火锅", pinyin: "huǒ guō",   translation: "hotpot" },
  { hanzi: "现在", pinyin: "xiàn zài",  translation: "agora" },
  { hanzi: "手机", pinyin: "shǒu jī",   translation: "celular" },
  { hanzi: "律师", pinyin: "lǜ shī",    translation: "advogado(a)" },
  { hanzi: "冰",   pinyin: "bīng",      translation: "gelo" },
  { hanzi: "树",   pinyin: "shù",       translation: "árvore" },
  { hanzi: "地",   pinyin: "dì",        translation: "terra / chão" },
  { hanzi: "天",   pinyin: "tiān",      translation: "céu" },
  { hanzi: "晚上", pinyin: "wǎn shàng", translation: "noite" },
  { hanzi: "中文", pinyin: "zhōng wén", translation: "chinês (idioma)" },
  { hanzi: "英文", pinyin: "yīng wén",  translation: "inglês" },
  { hanzi: "韩文", pinyin: "hán wén",   translation: "coreano" },
  { hanzi: "日文", pinyin: "rì wén",    translation: "japonês" },
  { hanzi: "家",   pinyin: "jiā",       translation: "casa" },
  { hanzi: "学校", pinyin: "xué xiào",  translation: "escola" },
  { hanzi: "我",   pinyin: "wǒ",        translation: "eu" },
  { hanzi: "你",   pinyin: "nǐ",        translation: "você" },
  { hanzi: "他",   pinyin: "tā",        translation: "ele" },
  { hanzi: "她",   pinyin: "tā",        translation: "ela" },
  { hanzi: "我们", pinyin: "wǒ men",    translation: "nós" },
  { hanzi: "你们", pinyin: "nǐ men",    translation: "vós / vocês" },
  { hanzi: "他们", pinyin: "tā men",    translation: "eles / elas" },
  { hanzi: "看",   pinyin: "kàn",       translation: "ver / olhar" },
  { hanzi: "有",   pinyin: "yǒu",       translation: "ter / haver" },
  { hanzi: "妻子", pinyin: "qī zi",     translation: "esposa" },
  { hanzi: "丈夫", pinyin: "zhàng fu",  translation: "esposo / marido" },
  { hanzi: "儿子", pinyin: "ér zi",     translation: "filho" },
  { hanzi: "女儿", pinyin: "nǚ ér",     translation: "filha" },
  { hanzi: "不",   pinyin: "bù",        translation: "não" },
  { hanzi: "走",   pinyin: "zǒu",       translation: "andar / caminhar" },
  { hanzi: "上帝", pinyin: "shàng dì",  translation: "Deus" },
  { hanzi: "汽车", pinyin: "qì chē",    translation: "carro" },
  { hanzi: "说",     pinyin: "shuō",      translation: "falar / dizer" },
  { hanzi: "医生",   pinyin: "yī shēng",  translation: "médico(a)" },
  { hanzi: "不客气", pinyin: "bù kè qi",  translation: "de nada" },
  { hanzi: "对不起", pinyin: "duì bu qǐ", translation: "desculpa" },
  { hanzi: "是",     pinyin: "shì",       translation: "ser (é)" },
  { hanzi: "在",     pinyin: "zài",       translation: "estar (em)" },
  { hanzi: "美国",   pinyin: "měi guó",   translation: "Estados Unidos" },
  { hanzi: "巴西",   pinyin: "bā xī",     translation: "Brasil" },
  { hanzi: "牛奶",   pinyin: "niú nǎi",   translation: "leite" },
  { hanzi: "茶",     pinyin: "chá",       translation: "chá" },
  { hanzi: "奶茶",   pinyin: "nǎi chá",   translation: "chá com leite" },
  { hanzi: "钱包",   pinyin: "qián bāo",  translation: "carteira" },
  { hanzi: "肉",     pinyin: "ròu",       translation: "carne" },
  { hanzi: "一",     pinyin: "yī",        translation: "um (1)" },
  { hanzi: "二",     pinyin: "èr",        translation: "dois (2)" },
  { hanzi: "三",     pinyin: "sān",       translation: "três (3)" },
  { hanzi: "四",     pinyin: "sì",        translation: "quatro (4)" },
  { hanzi: "五",     pinyin: "wǔ",        translation: "cinco (5)" },
  { hanzi: "六",     pinyin: "liù",       translation: "seis (6)" },
  { hanzi: "七",     pinyin: "qī",        translation: "sete (7)" },
  { hanzi: "八",     pinyin: "bā",        translation: "oito (8)" },
  { hanzi: "九",     pinyin: "jiǔ",       translation: "nove (9)" },
  { hanzi: "十",     pinyin: "shí",       translation: "dez (10)" },
  { hanzi: "杯子",   pinyin: "bēi zi",    translation: "copo" },
  { hanzi: "第一",   pinyin: "dì yī",     translation: "primeiro" },
  { hanzi: "第二",   pinyin: "dì èr",     translation: "segundo" },
  { hanzi: "第三",   pinyin: "dì sān",    translation: "terceiro" },
  { hanzi: "这里",   pinyin: "zhè lǐ",    translation: "aqui" },
  { hanzi: "那里",   pinyin: "nà lǐ",     translation: "ali / lá" },
  { hanzi: "课",     pinyin: "kè",        translation: "aula" },
  { hanzi: "音乐",   pinyin: "yīn yuè",   translation: "música" },
  { hanzi: "鱼",     pinyin: "yú",        translation: "peixe" },
  { hanzi: "黑色",   pinyin: "hēi sè",    translation: "preto" },
  { hanzi: "白色",   pinyin: "bái sè",    translation: "branco" },
];
