// Flashcard word bank, organized into decks.
//
// Each card has:
//   hanzi       -> the Chinese character(s)
//   pinyin      -> the romanized pronunciation (with tones)
//   translation -> the meaning in Portuguese
//   emoji       -> optional symbol shown when the card is revealed
//
// To create a new deck: define a list and add it to DECKS at the bottom.

// --- Deck: Numbers (1 to 10) ---
const NUMBERS = [
  { hanzi: "一", pinyin: "yī",  translation: "um (1)",    emoji: "1️⃣" },
  { hanzi: "二", pinyin: "èr",  translation: "dois (2)",  emoji: "2️⃣" },
  { hanzi: "三", pinyin: "sān", translation: "três (3)",  emoji: "3️⃣" },
  { hanzi: "四", pinyin: "sì",  translation: "quatro (4)", emoji: "4️⃣" },
  { hanzi: "五", pinyin: "wǔ",  translation: "cinco (5)", emoji: "5️⃣" },
  { hanzi: "六", pinyin: "liù", translation: "seis (6)",  emoji: "6️⃣" },
  { hanzi: "七", pinyin: "qī",  translation: "sete (7)",  emoji: "7️⃣" },
  { hanzi: "八", pinyin: "bā",  translation: "oito (8)",  emoji: "8️⃣" },
  { hanzi: "九", pinyin: "jiǔ", translation: "nove (9)",  emoji: "9️⃣" },
  { hanzi: "十", pinyin: "shí", translation: "dez (10)",  emoji: "🔟" },
];

// --- Deck: General (full vocabulary; includes the numbers in their place) ---
const GENERAL = [
  { hanzi: "你好", pinyin: "nǐ hǎo",    translation: "olá",            emoji: "👋" },
  { hanzi: "谢谢", pinyin: "xiè xie",   translation: "obrigado(a)",    emoji: "🙏" },
  { hanzi: "再见", pinyin: "zài jiàn",  translation: "até logo / tchau", emoji: "👋" },
  { hanzi: "爱",   pinyin: "ài",        translation: "amor / amar",    emoji: "❤️" },
  { hanzi: "水",   pinyin: "shuǐ",      translation: "água",           emoji: "💧" },
  { hanzi: "朋友", pinyin: "péng you",  translation: "amigo(a)",       emoji: "👫" },
  { hanzi: "中国", pinyin: "zhōng guó", translation: "China",          emoji: "🇨🇳" },
  { hanzi: "学生", pinyin: "xué sheng", translation: "estudante",      emoji: "🎓" },
  { hanzi: "老师", pinyin: "lǎo shī",   translation: "professor(a)",   emoji: "👩‍🏫" },
  { hanzi: "火车", pinyin: "huǒ chē",   translation: "trem",           emoji: "🚆" },
  { hanzi: "早餐", pinyin: "zǎo cān",   translation: "café da manhã",  emoji: "🥐" },
  { hanzi: "午餐", pinyin: "wǔ cān",    translation: "almoço",         emoji: "🍱" },
  { hanzi: "晚餐", pinyin: "wǎn cān",   translation: "jantar",         emoji: "🍽️" },
  { hanzi: "火",   pinyin: "huǒ",       translation: "fogo",           emoji: "🔥" },
  { hanzi: "火锅", pinyin: "huǒ guō",   translation: "hotpot",         emoji: "🍲" },
  { hanzi: "现在", pinyin: "xiàn zài",  translation: "agora",          emoji: "⏰" },
  { hanzi: "手机", pinyin: "shǒu jī",   translation: "celular",        emoji: "📱" },
  { hanzi: "律师", pinyin: "lǜ shī",    translation: "advogado(a)",    emoji: "⚖️" },
  { hanzi: "冰",   pinyin: "bīng",      translation: "gelo",           emoji: "🧊" },
  { hanzi: "树",   pinyin: "shù",       translation: "árvore",         emoji: "🌳" },
  { hanzi: "地",   pinyin: "dì",        translation: "terra / chão",   emoji: "🌍" },
  { hanzi: "天",   pinyin: "tiān",      translation: "céu",            emoji: "☁️" },
  { hanzi: "晚上", pinyin: "wǎn shàng", translation: "noite",          emoji: "🌙" },
  { hanzi: "中文", pinyin: "zhōng wén", translation: "chinês (idioma)", emoji: "🇨🇳" },
  { hanzi: "英文", pinyin: "yīng wén",  translation: "inglês",         emoji: "🇬🇧" },
  { hanzi: "韩文", pinyin: "hán wén",   translation: "coreano",        emoji: "🇰🇷" },
  { hanzi: "日文", pinyin: "rì wén",    translation: "japonês",        emoji: "🇯🇵" },
  { hanzi: "家",   pinyin: "jiā",       translation: "casa",           emoji: "🏠" },
  { hanzi: "学校", pinyin: "xué xiào",  translation: "escola",         emoji: "🏫" },
  { hanzi: "我",   pinyin: "wǒ",        translation: "eu" },
  { hanzi: "你",   pinyin: "nǐ",        translation: "você" },
  { hanzi: "他",   pinyin: "tā",        translation: "ele",            emoji: "👨" },
  { hanzi: "她",   pinyin: "tā",        translation: "ela",            emoji: "👩" },
  { hanzi: "我们", pinyin: "wǒ men",    translation: "nós" },
  { hanzi: "你们", pinyin: "nǐ men",    translation: "vós / vocês" },
  { hanzi: "他们", pinyin: "tā men",    translation: "eles / elas" },
  { hanzi: "看",   pinyin: "kàn",       translation: "ver / olhar",    emoji: "👀" },
  { hanzi: "有",   pinyin: "yǒu",       translation: "ter / haver" },
  { hanzi: "妻子", pinyin: "qī zi",     translation: "esposa",         emoji: "👰" },
  { hanzi: "丈夫", pinyin: "zhàng fu",  translation: "esposo / marido", emoji: "🤵" },
  { hanzi: "儿子", pinyin: "ér zi",     translation: "filho",          emoji: "👦" },
  { hanzi: "女儿", pinyin: "nǚ ér",     translation: "filha",          emoji: "👧" },
  { hanzi: "不",   pinyin: "bù",        translation: "não",            emoji: "🚫" },
  { hanzi: "走",   pinyin: "zǒu",       translation: "andar / caminhar", emoji: "🚶" },
  { hanzi: "上帝", pinyin: "shàng dì",  translation: "Deus",           emoji: "✝️" },
  { hanzi: "汽车", pinyin: "qì chē",    translation: "carro",          emoji: "🚗" },
  { hanzi: "说",     pinyin: "shuō",      translation: "falar / dizer",  emoji: "🗣️" },
  { hanzi: "医生",   pinyin: "yī shēng",  translation: "médico(a)",      emoji: "👨‍⚕️" },
  { hanzi: "不客气", pinyin: "bù kè qi",  translation: "de nada",        emoji: "😊" },
  { hanzi: "对不起", pinyin: "duì bu qǐ", translation: "desculpa",       emoji: "🙇" },
  { hanzi: "是",     pinyin: "shì",       translation: "ser (é)" },
  { hanzi: "在",     pinyin: "zài",       translation: "estar (em)",     emoji: "📍" },
  { hanzi: "美国",   pinyin: "měi guó",   translation: "Estados Unidos", emoji: "🇺🇸" },
  { hanzi: "巴西",   pinyin: "bā xī",     translation: "Brasil",         emoji: "🇧🇷" },
  { hanzi: "牛奶",   pinyin: "niú nǎi",   translation: "leite",          emoji: "🥛" },
  { hanzi: "茶",     pinyin: "chá",       translation: "chá",            emoji: "🍵" },
  { hanzi: "奶茶",   pinyin: "nǎi chá",   translation: "chá com leite",  emoji: "🧋" },
  { hanzi: "钱包",   pinyin: "qián bāo",  translation: "carteira",       emoji: "👛" },
  { hanzi: "肉",     pinyin: "ròu",       translation: "carne",          emoji: "🍖" },
  ...NUMBERS,
  { hanzi: "杯子",   pinyin: "bēi zi",    translation: "copo",           emoji: "🥤" },
  { hanzi: "第一",   pinyin: "dì yī",     translation: "primeiro",       emoji: "🥇" },
  { hanzi: "第二",   pinyin: "dì èr",     translation: "segundo",        emoji: "🥈" },
  { hanzi: "第三",   pinyin: "dì sān",    translation: "terceiro",       emoji: "🥉" },
  { hanzi: "这里",   pinyin: "zhè lǐ",    translation: "aqui",           emoji: "👇" },
  { hanzi: "那里",   pinyin: "nà lǐ",     translation: "ali / lá",       emoji: "👉" },
  { hanzi: "课",     pinyin: "kè",        translation: "aula",           emoji: "📚" },
  { hanzi: "音乐",   pinyin: "yīn yuè",   translation: "música",         emoji: "🎵" },
  { hanzi: "鱼",     pinyin: "yú",        translation: "peixe",          emoji: "🐟" },
  { hanzi: "吃",     pinyin: "chī",       translation: "comer",          emoji: "🍴" },
  { hanzi: "鸡蛋",   pinyin: "jī dàn",    translation: "ovo(s)",         emoji: "🥚" },
  { hanzi: "的",     pinyin: "de",        translation: "(partícula de posse) de" },
  { hanzi: "吗",     pinyin: "ma",        translation: "(partícula de pergunta)", emoji: "❓" },
  { hanzi: "了",     pinyin: "le",        translation: "(partícula de ação concluída)" },
  { hanzi: "个",     pinyin: "ge",        translation: "(classificador genérico)" },
  { hanzi: "和",     pinyin: "hé",        translation: "e (conjunção)" },
  { hanzi: "也",     pinyin: "yě",        translation: "também" },
  { hanzi: "很",     pinyin: "hěn",       translation: "muito" },
  { hanzi: "喝",     pinyin: "hē",        translation: "beber",          emoji: "🥂" },
  { hanzi: "喜欢",   pinyin: "xǐ huan",   translation: "gostar (de)",    emoji: "👍" },
  { hanzi: "想",     pinyin: "xiǎng",     translation: "querer / pensar", emoji: "💭" },
  { hanzi: "猫",     pinyin: "māo",       translation: "gato",           emoji: "🐱" },
  { hanzi: "狗",     pinyin: "gǒu",       translation: "cachorro",       emoji: "🐶" },
  { hanzi: "只",     pinyin: "zhī",       translation: "(classificador de animais)" },
  { hanzi: "早上好", pinyin: "zǎo shang hǎo", translation: "bom dia",    emoji: "🌅" },
  { hanzi: "晚上好", pinyin: "wǎn shang hǎo", translation: "boa noite (cumprimento)", emoji: "🌃" },
  { hanzi: "巴西人", pinyin: "bā xī rén",  translation: "brasileiro(a)",  emoji: "🇧🇷" },
  { hanzi: "咖啡",   pinyin: "kā fēi",     translation: "café",           emoji: "☕" },
  { hanzi: "马",     pinyin: "mǎ",         translation: "cavalo",         emoji: "🐴" },
  { hanzi: "妈妈",   pinyin: "mā ma",      translation: "mãe",            emoji: "👩‍👦" },
  { hanzi: "雨",     pinyin: "yǔ",         translation: "chuva",          emoji: "🌧️" },
];

// --- Deck: General II (extra vocabulary) ---
const GENERAL_2 = [
  { hanzi: "新", pinyin: "xīn",  translation: "novo",              emoji: "🆕" },
  { hanzi: "多", pinyin: "duō",  translation: "muito (quantidade)" },
  { hanzi: "少", pinyin: "shǎo", translation: "pouco" },
  { hanzi: "今天", pinyin: "jīn tiān",  translation: "hoje",       emoji: "📅" },
  { hanzi: "昨天", pinyin: "zuó tiān",  translation: "ontem" },
  { hanzi: "明天", pinyin: "míng tiān", translation: "amanhã" },
  { hanzi: "黑色",   pinyin: "hēi sè",    translation: "preto",    emoji: "⚫" },
  { hanzi: "白色",   pinyin: "bái sè",    translation: "branco",   emoji: "⚪" },
  { hanzi: "厨房",   pinyin: "chú fáng",     translation: "cozinha",  emoji: "🍳" },
  { hanzi: "生活",   pinyin: "shēng huó",    translation: "vida" },
  { hanzi: "死",     pinyin: "sǐ",           translation: "morrer / morte", emoji: "💀" },
  { hanzi: "洗手间", pinyin: "xǐ shǒu jiān", translation: "banheiro", emoji: "🚽" },
  { hanzi: "苹果",   pinyin: "píng guǒ",     translation: "maçã",     emoji: "🍎" },
  { hanzi: "饺子",   pinyin: "jiǎo zi",      translation: "guioza",   emoji: "🥟" },
  { hanzi: "奶奶",   pinyin: "nǎi nai",      translation: "vovó (paterno)", emoji: "👵" },
  { hanzi: "爷爷",   pinyin: "yé ye",        translation: "vovô (materno)", emoji: "👴" },
  { hanzi: "来",     pinyin: "lái",          translation: "vir",              emoji: "🙋" },
  { hanzi: "回",     pinyin: "huí",          translation: "voltar",           emoji: "↩️" },
  { hanzi: "去",     pinyin: "qù",           translation: "ir",               emoji: "➡️" },
  { hanzi: "钱",     pinyin: "qián",         translation: "dinheiro",         emoji: "💰" },
  { hanzi: "能",     pinyin: "néng",         translation: "poder (ser capaz)" },
  { hanzi: "知道",   pinyin: "zhī dào",      translation: "saber",            emoji: "💡" },
  { hanzi: "游泳",   pinyin: "yóu yǒng",     translation: "nadar",            emoji: "🏊" },
  { hanzi: "大",     pinyin: "dà",           translation: "grande",           emoji: "🐘" },
  { hanzi: "小",     pinyin: "xiǎo",         translation: "pequeno",          emoji: "🐭" },
  { hanzi: "冷",     pinyin: "lěng",         translation: "frio",             emoji: "🥶" },
  { hanzi: "热",     pinyin: "rè",           translation: "quente",           emoji: "🥵" },
  { hanzi: "漂亮",   pinyin: "piào liang",   translation: "bonito",           emoji: "😍" },
  { hanzi: "丑",     pinyin: "chǒu",         translation: "feio",             emoji: "🤢" },
  { hanzi: "高兴",   pinyin: "gāo xìng",     translation: "feliz",            emoji: "😄" },
  { hanzi: "伤心",   pinyin: "shāng xīn",    translation: "triste",           emoji: "😢" },
];

// --- Deck: Bible (Bible-related vocabulary) ---
const BIBLE = [
  { hanzi: "圣经",     pinyin: "shèng jīng",   translation: "Bíblia",        emoji: "📖" },
  { hanzi: "上帝",     pinyin: "shàng dì",     translation: "Deus",          emoji: "✝️" },
  { hanzi: "耶稣基督", pinyin: "yē sū jī dū",  translation: "Jesus Cristo",  emoji: "✝️" },
  { hanzi: "福音",     pinyin: "fú yīn",       translation: "Evangelho",     emoji: "🕊️" },
  { hanzi: "创世记",   pinyin: "chuàng shì jì", translation: "Gênesis",      emoji: "🌍" },
  { hanzi: "出埃及记", pinyin: "chū āi jí jì", translation: "Êxodo",         emoji: "🏜️" },
  { hanzi: "诗篇",     pinyin: "shī piān",     translation: "Salmos",        emoji: "🎶" },
  { hanzi: "启示录",   pinyin: "qǐ shì lù",    translation: "Apocalipse",    emoji: "🔥" },
];

// --- Deck: Colors ---
const COLORS = [
  { hanzi: "白色", pinyin: "bái sè",   translation: "branco",   emoji: "⚪" },
  { hanzi: "黑色", pinyin: "hēi sè",   translation: "preto",    emoji: "⚫" },
  { hanzi: "红色", pinyin: "hóng sè",  translation: "vermelho", emoji: "🔴" },
  { hanzi: "绿色", pinyin: "lǜ sè",    translation: "verde",    emoji: "🟢" },
  { hanzi: "蓝色", pinyin: "lán sè",   translation: "azul",     emoji: "🔵" },
  { hanzi: "黄色", pinyin: "huáng sè", translation: "amarelo",  emoji: "🟡" },
  { hanzi: "棕色", pinyin: "zōng sè",  translation: "marrom",   emoji: "🟤" },
  { hanzi: "灰色", pinyin: "huī sè",   translation: "cinza",    emoji: "⚫" },
  { hanzi: "粉色", pinyin: "fěn sè",   translation: "rosa",     emoji: "🌸" },
];

// --- Deck: Phrases (sentences using the General vocabulary) ---
const PHRASES = [
  { hanzi: "我是学生。",        pinyin: "Wǒ shì xuéshēng.",        translation: "Eu sou estudante." },
  { hanzi: "你好，老师！",      pinyin: "Nǐ hǎo, lǎoshī!",         translation: "Olá, professor(a)!" },
  { hanzi: "我爱你。",          pinyin: "Wǒ ài nǐ.",               translation: "Eu te amo." },
  { hanzi: "他是我的朋友。",    pinyin: "Tā shì wǒ de péngyou.",   translation: "Ele é meu amigo." },
  { hanzi: "今天我吃鱼。",      pinyin: "Jīntiān wǒ chī yú.",      translation: "Hoje eu como peixe." },
  { hanzi: "我们喝茶。",        pinyin: "Wǒmen hē chá.",           translation: "Nós bebemos chá." },
  { hanzi: "他在学校。",        pinyin: "Tā zài xuéxiào.",         translation: "Ele está na escola." },
  { hanzi: "现在是晚上。",      pinyin: "Xiànzài shì wǎnshàng.",   translation: "Agora é de noite." },
  { hanzi: "我说中文。",        pinyin: "Wǒ shuō zhōngwén.",       translation: "Eu falo chinês." },
  { hanzi: "我的妻子是医生。",  pinyin: "Wǒ de qīzi shì yīshēng.", translation: "Minha esposa é médica." },
  { hanzi: "谢谢！不客气。",    pinyin: "Xièxie! Bù kèqi.",        translation: "Obrigado! De nada." },
  { hanzi: "对不起，我现在走。", pinyin: "Duìbuqǐ, wǒ xiànzài zǒu.", translation: "Desculpa, eu vou agora." },
  { hanzi: "这是我的家。",      pinyin: "Zhè shì wǒ de jiā.",      translation: "Esta é a minha casa." },
  { hanzi: "我有一个手机。",    pinyin: "Wǒ yǒu yí ge shǒujī.",    translation: "Eu tenho um celular." },
  { hanzi: "明天我们吃火锅。",  pinyin: "Míngtiān wǒmen chī huǒguō.", translation: "Amanhã nós comemos hotpot." },
  { hanzi: "我喜欢音乐。",      pinyin: "Wǒ xǐhuan yīnyuè.",       translation: "Eu gosto de música." },
  { hanzi: "你好吗？",          pinyin: "Nǐ hǎo ma?",              translation: "Tudo bem?" },
  { hanzi: "我很好，谢谢。",    pinyin: "Wǒ hěn hǎo, xièxie.",     translation: "Estou muito bem, obrigado." },
  { hanzi: "你喜欢茶吗？",      pinyin: "Nǐ xǐhuan chá ma?",       translation: "Você gosta de chá?" },
  { hanzi: "我想喝水。",        pinyin: "Wǒ xiǎng hē shuǐ.",       translation: "Quero beber água." },
  { hanzi: "我和你是朋友。",    pinyin: "Wǒ hé nǐ shì péngyou.",   translation: "Eu e você somos amigos." },
  { hanzi: "他也是学生。",      pinyin: "Tā yě shì xuéshēng.",     translation: "Ele também é estudante." },
  { hanzi: "我喜欢喝奶茶。",    pinyin: "Wǒ xǐhuan hē nǎichá.",    translation: "Eu gosto de beber chá com leite." },
  { hanzi: "你说中文吗？",      pinyin: "Nǐ shuō zhōngwén ma?",    translation: "Você fala chinês?" },
  { hanzi: "我不喝牛奶。",      pinyin: "Wǒ bù hē niúnǎi.",        translation: "Eu não bebo leite." },
  { hanzi: "今天我喝了茶。",    pinyin: "Jīntiān wǒ hē le chá.",   translation: "Hoje eu bebi chá." },
  { hanzi: "我有一个儿子。",    pinyin: "Wǒ yǒu yí ge érzi.",      translation: "Eu tenho um filho." },
  { hanzi: "他的妻子很好。",    pinyin: "Tā de qīzi hěn hǎo.",     translation: "A esposa dele é muito legal." },
  { hanzi: "我喜欢中文课。",    pinyin: "Wǒ xǐhuan zhōngwén kè.",  translation: "Eu gosto da aula de chinês." },
  { hanzi: "现在我想走。",      pinyin: "Xiànzài wǒ xiǎng zǒu.",   translation: "Agora eu quero ir embora." },
  { hanzi: "这是你的手机吗？",  pinyin: "Zhè shì nǐ de shǒujī ma?", translation: "Este é o seu celular?" },
  { hanzi: "我的钱包是黑色的。", pinyin: "Wǒ de qiánbāo shì hēisè de.", translation: "Minha carteira é preta." },
  { hanzi: "我想吃鸡蛋。",      pinyin: "Wǒ xiǎng chī jīdàn.",     translation: "Quero comer ovos." },
  { hanzi: "我也喜欢音乐。",    pinyin: "Wǒ yě xǐhuan yīnyuè.",    translation: "Eu também gosto de música." },
  { hanzi: "他在美国。",        pinyin: "Tā zài Měiguó.",          translation: "Ele está nos Estados Unidos." },
  { hanzi: "你有钱包吗？",      pinyin: "Nǐ yǒu qiánbāo ma?",      translation: "Você tem carteira?" },
  { hanzi: "我有一只猫。",      pinyin: "Wǒ yǒu yì zhī māo.",      translation: "Eu tenho um gato." },
  { hanzi: "我喜欢猫和狗。",    pinyin: "Wǒ xǐhuan māo hé gǒu.",   translation: "Eu gosto de gatos e cachorros." },
  { hanzi: "他有一只狗。",      pinyin: "Tā yǒu yì zhī gǒu.",      translation: "Ele tem um cachorro." },
];

// --- Deck: Phrases II (sentences using General II + words/particles from General) ---
const PHRASES_2 = [
  { hanzi: "我喜欢吃饺子。",     pinyin: "Wǒ xǐhuan chī jiǎozi.",  translation: "Eu gosto de comer guioza." },
  { hanzi: "这是我的奶奶。",     pinyin: "Zhè shì wǒ de nǎinai.",  translation: "Esta é a minha avó." },
  { hanzi: "他是我的爷爷。",     pinyin: "Tā shì wǒ de yéye.",     translation: "Ele é o meu avô." },
  { hanzi: "洗手间在那里。",     pinyin: "Xǐshǒujiān zài nàli.",   translation: "O banheiro fica ali." },
  { hanzi: "我想吃苹果。",       pinyin: "Wǒ xiǎng chī píngguǒ.",  translation: "Quero comer maçã." },
  { hanzi: "我在厨房。",         pinyin: "Wǒ zài chúfáng.",        translation: "Estou na cozinha." },
  { hanzi: "这是新手机。",       pinyin: "Zhè shì xīn shǒujī.",    translation: "Este é um celular novo." },
  { hanzi: "我有很多朋友。",     pinyin: "Wǒ yǒu hěn duō péngyou.", translation: "Eu tenho muitos amigos." },
  { hanzi: "他吃了很多饺子。",   pinyin: "Tā chī le hěn duō jiǎozi.", translation: "Ele comeu muitas guiozas." },
  { hanzi: "我的朋友很少。",     pinyin: "Wǒ de péngyou hěn shǎo.", translation: "Tenho poucos amigos." },
  { hanzi: "奶奶在厨房。",       pinyin: "Nǎinai zài chúfáng.",    translation: "A vovó está na cozinha." },
  { hanzi: "爷爷的生活很好。",   pinyin: "Yéye de shēnghuó hěn hǎo.", translation: "A vida do vovô é muito boa." },
  { hanzi: "这里有洗手间吗？",   pinyin: "Zhèli yǒu xǐshǒujiān ma?", translation: "Aqui tem banheiro?" },
  { hanzi: "我不想死。",         pinyin: "Wǒ bù xiǎng sǐ.",        translation: "Eu não quero morrer." },
  { hanzi: "奶奶和爷爷在家。",   pinyin: "Nǎinai hé yéye zài jiā.", translation: "A vovó e o vovô estão em casa." },
];

// --- Decks shown on the home screen (in display order) ---
const DECKS = [
  { id: "general",   name: "Geral",     nameZh: "综合",  desc: "Todo o vocabulário",  cards: GENERAL },
  { id: "general2",  name: "Geral II",  nameZh: "综合二", desc: "Vocabulário extra",   cards: GENERAL_2 },
  { id: "numbers",   name: "Números",   nameZh: "数字",  desc: "De 1 a 10",           cards: NUMBERS },
  { id: "phrases",   name: "Frases",    nameZh: "句子",  desc: "Sentenças variadas",  cards: PHRASES },
  { id: "phrases2",  name: "Frases II", nameZh: "句子二", desc: "Frases do Geral II",  cards: PHRASES_2 },
  { id: "bible",     name: "Bíblia",    nameZh: "圣经",  desc: "Vocabulário bíblico", cards: BIBLE },
  { id: "colors",    name: "Cores",     nameZh: "颜色",  desc: "As cores",            cards: COLORS },
  // PINYIN_SYLLABLES comes from pinyin_data.js (loaded before this file).
  { id: "pinyin",    name: "Tabela Pinyin", nameZh: "拼音", desc: "O som de cada sílaba", cards: PINYIN_SYLLABLES },
];
